version: '2'
services:
  kibana:
    tty: true
    image: harbor.hm.dm.ad/logmanagement/kibana:${kb_version}
    environment:
      KB_CONFIG_ELASTICSEARCH_URL: http://elasticsearch-client:9200
      KB_CONFIG_ELASTICSEARCH_USERNAME: kibana
      KB_CONFIG_ELASTICSEARCH_PASSWORD: ${kibana_password}
      KB_CONFIG_DEFAULTAPPID: ${default_app_id}
      KB_CONFIG_DEFAULTROUTE: ${default_route}
      KB_CONFIG_BASEPATH: ${default_base_path}
      KB_CONFIG_AUTOCOMPLETETIMEOUT: ${autocomplete_timeout}
      KB_CONFIG_AUTOCOMPLETETERMINATEAFTER: ${autocomplete_terminated_after}
      KB_MONITORING_ENABLED: ${enable_monitoring}
      KB_MONITORING_UIENABLED: ${monitoring_ui}
      KB_CONFIG_ELASTICSEARCH_REQUESTTIMEOUT: 300000
      KB_CONFIG_ENCRYPTIONKEY: ${encryption_key}
      COMMIT_ID: ${commit_id}
    external_links:
       - ${client_stack}:elasticsearch-client
    ${mem_limit}
    cpu_shares: ${cpu_shares}
    labels:
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$$$${stack_name}/$$$${service_name}
      io.rancher.scheduler.affinity:host_label: ${label_scheduling}
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: ${global_scheduling}